/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import java.io.IOException;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import persistencia.Buscas;
import persistencia.LeitorArquivo;
import persistencia.OrdenaVetor;

/**
 *
 * @author Aluno
 */
public class MenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form MenuInicial
     */
    public MenuInicial() {
        initComponents();
        setLocationRelativeTo(null);

    }

    public String[] selecionaIdioma() throws IOException, Exception{
        int idioma = jComboBoxIdiomas.getSelectedIndex();

        if (idioma == 0) {
            throw new Exception("Selecione um idioma a ser usado.");
        } else {
            return LeitorArquivo.leitorArquivo(jComboBoxIdiomas.getSelectedItem() + ".txt");
        }
    }

    public String palavraABuscar() {
        String palavraABuscar = jTextFieldPalavra.getText();
        return palavraABuscar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxIdiomas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonSelection = new javax.swing.JRadioButton();
        jRadioButtonBubble = new javax.swing.JRadioButton();
        jRadioButtonInsertion = new javax.swing.JRadioButton();
        jRadioButtonQuick = new javax.swing.JRadioButton();
        jRadioButtonMerge = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldPalavra = new javax.swing.JTextField();
        jLabelResposta = new javax.swing.JLabel();
        jLabelTempo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("BUSCA E ORDENAÇÃO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel3.setText("Selecione o idioma para efetuar a busca de palavras:");

        jComboBoxIdiomas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Português (BR)", "English (USA)", "Basque" }));

        jLabel4.setText("Escolha o modo de ordenação que prefira usar:");

        buttonGroup1.add(jRadioButtonSelection);
        jRadioButtonSelection.setSelected(true);
        jRadioButtonSelection.setText("Selection Sort");

        buttonGroup1.add(jRadioButtonBubble);
        jRadioButtonBubble.setText("Bubble Sort");

        buttonGroup1.add(jRadioButtonInsertion);
        jRadioButtonInsertion.setText("Insertion Sort");

        buttonGroup1.add(jRadioButtonQuick);
        jRadioButtonQuick.setText("Quick Sort*");

        buttonGroup1.add(jRadioButtonMerge);
        jRadioButtonMerge.setText("Merge Sort");

        jLabel5.setText("Qual tipo de busca efetuar?");

        jButton1.setText("Sequencial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText("|");

        jButton2.setText("Binária");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Qual palavra buscar no dicionário?");

        jTextFieldPalavra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPalavraActionPerformed(evt);
            }
        });

        jLabelResposta.setForeground(new java.awt.Color(153, 153, 153));
        jLabelResposta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResposta.setText("RESPOSTA");

        jLabelTempo.setForeground(new java.awt.Color(153, 153, 153));
        jLabelTempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonSelection)
                            .addComponent(jRadioButtonQuick)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonBubble)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonInsertion)
                                    .addComponent(jRadioButtonMerge))
                                .addGap(18, 18, 18)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(71, 71, 71)
                            .addComponent(jLabel3)
                            .addGap(29, 29, 29)
                            .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelTempo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelResposta, javax.swing.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxIdiomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldPalavra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jRadioButtonSelection))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonBubble)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonInsertion)
                        .addGap(8, 8, 8)
                        .addComponent(jRadioButtonMerge))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jLabel6)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonQuick)
                .addGap(65, 65, 65)
                .addComponent(jLabelResposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPalavraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPalavraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPalavraActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] dicionario;
        boolean resposta = false;
        long respostaTempo = 0;
        try {
            dicionario = selecionaIdioma();

            if (jRadioButtonSelection.isSelected()) {
                long tempoInicial = System.currentTimeMillis();
                OrdenaVetor.SelectionSort(dicionario);
                resposta = Buscas.buscaSequencial(palavraABuscar(), dicionario);
                long tempoFinal = (System.currentTimeMillis() - tempoInicial);
            } else if (jRadioButtonBubble.isSelected()) {
                long tempoInicial = System.currentTimeMillis();
                OrdenaVetor.bubbleSort(dicionario);
                resposta = Buscas.buscaSequencial(palavraABuscar(), dicionario);
                long tempoFinal = (System.currentTimeMillis() - tempoInicial);
            } else if (jRadioButtonInsertion.isSelected()) {
                long tempoInicial = System.currentTimeMillis();
                OrdenaVetor.insertionSort(dicionario);
                resposta = Buscas.buscaSequencial(palavraABuscar(), dicionario);
                long tempoFinal = (System.currentTimeMillis() - tempoInicial);
            } else if (jRadioButtonMerge.isSelected()) {
                long tempoInicial = System.currentTimeMillis();
                OrdenaVetor.mergeSort(0, dicionario);
                resposta = Buscas.buscaSequencial(palavraABuscar(), dicionario);
                long tempoFinal = (System.currentTimeMillis() - tempoInicial);
            } else if (jRadioButtonQuick.isSelected()) {
                long tempoInicial = System.currentTimeMillis();
                OrdenaVetor.quickSort(dicionario, 0, dicionario.length-1);
                resposta = Buscas.buscaSequencial(palavraABuscar(), dicionario);
                long tempoFinal = (System.currentTimeMillis() - tempoInicial);
                respostaTempo = tempoFinal;
            }
            if (resposta) {
            jLabelResposta.setText("A palavra buscada está no dicionário do idioma.");
        } else {
            jLabelResposta.setText("A palavra buscada não está no dicionário do idioma.");
        }
            jLabelTempo.setText("Tempo de execucao: " + respostaTempo + "ms");
        } catch (IOException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione um idioma a ser usado.");
            ex.printStackTrace();
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String[] dicionario;
        try {
            dicionario = selecionaIdioma(); 
        boolean resposta = false;
        long respostaTempo = 0;
        if (jRadioButtonSelection.isSelected()) {
            long tempoInicial = System.currentTimeMillis();
            OrdenaVetor.SelectionSort(dicionario);
            resposta = Buscas.buscaBinaria(palavraABuscar(), dicionario);
            long tempoFinal = (System.currentTimeMillis() - tempoInicial);
        } else if (jRadioButtonBubble.isSelected()) {
            long tempoInicial = System.currentTimeMillis();
            OrdenaVetor.bubbleSort(dicionario);
            resposta = Buscas.buscaBinaria(palavraABuscar(), dicionario);
            long tempoFinal = (System.currentTimeMillis() - tempoInicial);
        } else if (jRadioButtonInsertion.isSelected()) {
            long tempoInicial = System.currentTimeMillis();
            OrdenaVetor.insertionSort(dicionario);
            resposta = Buscas.buscaBinaria(palavraABuscar(), dicionario);
            long tempoFinal = (System.currentTimeMillis() - tempoInicial);
        } else if (jRadioButtonMerge.isSelected()) {
            long tempoInicial = System.currentTimeMillis();
            OrdenaVetor.mergeSort(dicionario.length, dicionario);
            resposta = Buscas.buscaBinaria(palavraABuscar(), dicionario);
            long tempoFinal = (System.currentTimeMillis() - tempoInicial);
        } else if (jRadioButtonQuick.isSelected()) {
            long tempoInicial = System.currentTimeMillis();
            OrdenaVetor.quickSort(dicionario, 0, dicionario.length-1);
            resposta = Buscas.buscaBinaria(palavraABuscar(), dicionario);
            long tempoFinal = (System.currentTimeMillis()- tempoInicial);
            respostaTempo = tempoFinal;
        }

        if (resposta) {
            jLabelResposta.setText("A palavra buscada está no dicionário do idioma.");
        } else {
            jLabelResposta.setText("A palavra buscada não está no dicionário do idioma.");
        }
        jLabelTempo.setText("Tempo de execucao: " + respostaTempo + "ms");
        
        
        
        } catch (IOException ex) {
            Logger.getLogger(MenuInicial.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecione um idioma a ser usado.");
            ex.printStackTrace();
        }
        
        
        

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxIdiomas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelResposta;
    private javax.swing.JLabel jLabelTempo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonBubble;
    private javax.swing.JRadioButton jRadioButtonInsertion;
    private javax.swing.JRadioButton jRadioButtonMerge;
    private javax.swing.JRadioButton jRadioButtonQuick;
    private javax.swing.JRadioButton jRadioButtonSelection;
    private javax.swing.JTextField jTextFieldPalavra;
    // End of variables declaration//GEN-END:variables
}
